import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    // Couleurs des badges ligue (classes dynamiques depuis LEAGUE_COLORS)
    "bg-zinc-700/50",
    "text-zinc-200",
    "border-zinc-500",
    "bg-amber-900/50",
    "text-amber-200",
    "border-amber-700",
    "bg-slate-600/50",
    "text-slate-200",
    "border-slate-500",
    "bg-amber-600/50",
    "text-amber-100",
    "border-amber-500",
    "bg-cyan-800/50",
    "text-cyan-200",
    "border-cyan-600",
    "bg-emerald-800/50",
    "text-emerald-200",
    "border-emerald-600",
    "bg-violet-600/50",
    "text-violet-100",
    "border-violet-500",
    "bg-rose-800/50",
    "text-rose-100",
    "border-rose-600",
    "bg-emerald-700/50",
    "text-emerald-100",
    "border-emerald-500",
    "bg-amber-500/60",
    "text-amber-950",
    "border-amber-400",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        border: "var(--border)",
        input: "var(--input)",
        destructive: "var(--destructive)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [],
} satisfies Config;
