require_relative '../../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'
use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../../node_modules/@capacitor/app'
  pod 'CapacitorBrowser', :path => '../../../node_modules/@capacitor/browser'
  pod 'CapacitorHaptics', :path => '../../../node_modules/@capacitor/haptics'
  pod 'CapacitorStatusBar', :path => '../../../node_modules/@capacitor/status-bar'
  pod 'CapawesomeCapacitorAppReview', :path => '../../../node_modules/@capawesome/capacitor-app-review'
  pod 'CapgoCapacitorSocialLogin', :path => '../../../node_modules/@capgo/capacitor-social-login'
end

target 'App' do
  capacitor_pods
  # Pods ajoutés par `npx cap sync ios`
end

post_install do |installer|
  assertDeploymentTarget(installer)

  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
        config.build_settings['CODE_SIGN_STYLE'] = 'Automatic'
        config.build_settings['CODE_SIGN_IDENTITY'] = ''
        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ''
      end
    end
  end
end
