export enum NotificationType {
  StreakAtRisk = 'streak_at_risk',
  FriendRequest = 'friend_request',
  FriendAccepted = 'friend_accepted',
  MessageNew = 'message_new',
  SessionComment = 'session_comment',
  FriendTraining = 'friend_training',
  FriendPr = 'friend_pr',
  WeeklyRecap = 'weekly_recap',
  TrainingReminder = 'training_reminder',
  ReferralUsed = 'referral_used',
  TshirtRewardUnlocked = 'tshirt_reward_unlocked',
  NewUserD1Morning = 'new_user_d1_morning',
  NewUserD1MiddayTrain = 'new_user_d1_midday_train',
  NewUserD1Referral = 'new_user_d1_referral',
  NewUserD1Evening = 'new_user_d1_evening',
}
